apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yaml
  - deployment.yaml
  - service.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: kube-tag-radar-config
    envs:
      - config.env
    files:
      - config.yaml
